linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
  unused:
    exported-fields-are-used: false

issues:
  exclude-use-default: false
